=== sumithomas25/pr1/XML/Coffeeschema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.example.org/Coffeeschema" 
xmlns:tns="http://www.example.org/Coffeeschema" elementFormDefault="qualified">

<complexType name="Coffeetype">
  <sequence>
  <element name="coffeeshop" type="tns:coffeetype" maxOccurs="20" minOccurs="1"></element>
  </sequence>
  </complexType>
  
  <complexType name="coffeetype">
  <sequence>
  <element name="name" type="string"></element>
  <element name="add" type="string"></element>
  <element name="cont"  type="tns:myCont"></element> 
  
  </sequence>
  
  <attribute name="cid" type="ID" use="required"> </attribute>
  
  </complexType>
  
  <element name="globalevent" type="tns:Coffeetype"></element>
  
  <simpleType name="myCont">
  <restriction base="integer">
  <pattern value="[0-9]{10}"></pattern>
  </restriction>
  </simpleType>
 


</schema>

=== sumithomas25/pr1/XML/NewCoffee.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:globalevent xmlns:tns="http://www.example.org/Coffeeschema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Coffeeschema Coffeeschema.xsd ">
  <tns:coffeeshop cid="C1">
    <tns:name>Starbucks Coffee</tns:name>
    <tns:add>Samrat Building, Ground, 100 Feet Rd, HAL 2nd Stage, Indiranagar, Bengaluru, Karnataka 560008</tns:add>
    <tns:cont>8787655322</tns:cont>
  </tns:coffeeshop>
  
  
  
 <tns:coffeeshop cid="C2">
    <tns:name>Third Wave Coffee Roasters</tns:name>
    <tns:add>4th Block, 1, 984, 80 Feet Rd, Maharaja Signal, Koramangala, Bengaluru, Karnataka 560034</tns:add>
    <tns:cont>9703625364</tns:cont>
  </tns:coffeeshop>
  
  
 <tns:coffeeshop cid="C3">
    <tns:name>Matteo Coffea</tns:name>
    <tns:add>2, Church Street, Mahatma Gandhi Rd, Bengaluru, Karnataka 560001</tns:add>
    <tns:cont>9113235863</tns:cont>
  </tns:coffeeshop>
  
  <tns:coffeeshop cid="C4">
    <tns:name>Hebbar's Coffee Shop</tns:name>
    <tns:add>109, Gundopanth St, KR Market, Mamulpet, Chickpet, Bengaluru, Karnataka 560002</tns:add>
    <tns:cont>9773235863</tns:cont>
  </tns:coffeeshop>
  
    <tns:coffeeshop cid="C5">
    <tns:name>Om Made Cafe</tns:name>
    <tns:add>No. 136, Evergreen PARC, Rooftop, 1st Cross Rd, 5th Block, Koramangala, Bengaluru, Karnataka 560095</tns:add>
    <tns:cont>9293235863</tns:cont>
  </tns:coffeeshop>
  
    <tns:coffeeshop cid="C6">
    <tns:name>KARMA KAAPI â€“ CAFFEINE STUDIO</tns:name>
    <tns:add>1st Floor, #81, 36th Cross Rd, 5th Block, Jayanagar, Bengaluru, Karnataka 560041</tns:add>
    <tns:cont>9945689243</tns:cont>
  </tns:coffeeshop>
  
  
  
  
  
</tns:globalevent>
